name: C-SHELL COMPILE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Clean previous build
        run: rm -rf build

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: cmake .. -B build

      - name: Build with CMake
        run: cmake --build build
