name: C-SHELL COMPILE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Cleanup
        run: rm -rf build/

      - name: Run build script
        run: ./build.sh
