name: C-SHELL COMPILE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Cleanup
        run: rm -rf build/
      
      - name: Create Build Platform
        run: mkdir -p build/

      - name: Run build script
        run: ./build.sh

  release:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install base-devel and cmake
        run: |
          pacman -Sy --noconfirm base-devel cmake git

      - name: Build and install package
        run: |
          # Allow makepkg to run without root
          useradd -m builder
          mkdir -p /home/builder/pkgbuild
          cp -r . /home/builder/pkgbuild/
          chown -R builder:builder /home/builder/pkgbuild
          cd /home/builder/pkgbuild
          sudo -u builder makepkg -si --noconfirm
